apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger-v2
  namespace: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logger
      version: v2
  template:
    metadata:
      labels:
        app: logger
        version: v2
    spec:
      containers:
        - name: logger
          image: busybox:latest
          command:
            - /bin/sh
            - -c
            - while true; do echo "$(date) - Host: $(hostname)" >> /log/output.txt; sleep 10; done
          volumeMounts:
            - name: log-volume
              mountPath: /log
      volumes:
        - name: log-volume
          emptyDir: {}
